Changes Text to be more simple and Website now Responsive
Boby900/front-website pull request #10
Opened 2023-01-15 12:49 UTC by maguzzz

* Changed the  `project description` to be more comprehensive 
* Changed About me text to be more readable on phones
* Fixed the website  `Responsivess`

2023-01-16 01:44 UTC, Boby900 requested changes

2023-01-16 01:44 UTC, Boby900 commented on index.css
> +    .info{
thanks @maguzzz ,
 but  this line of code is disrupting the text alignment,
![Screenshot (27)](https://user-images.githubusercontent.com/111265239/212581033-5cdf2f07-348f-42a5-b44f-35657b70b3e1.png)

2023-01-16 08:01 UTC, maguzzz commented
Ah sry looks like i changed the about me text after i fixed the responsiveness of the projects and forgot to check if its still works.

I will fix it today!!!

2023-01-17 07:47 UTC, Boby900 approved these changes

2023-01-17 07:47 UTC, merged

2023-01-17 07:47 UTC, Boby900 commented
thanks once again @maguzzz